CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"password" text NOT NULL,
	"mail" text,
	"role" text DEFAULT 'user',
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"last_login" timestamp,
	"profile_picture" text,
	"bio" text,
	"reset_token" text,
	"reset_token_expiry" timestamp,
	"email_verified" boolean DEFAULT false,
	"email_verification_token" text,
	"preferences" text,
	"two_factor_enabled" boolean DEFAULT false,
	"two_factor_secret" text,
	"oauth_provider" text,
	"oauth_id" text,
	"oauth_token" text,
	CONSTRAINT "users_username_unique" UNIQUE("username")
);
