CREATE TABLE "evenements" (
	"id" serial PRIMARY KEY NOT NULL,
	"title_evenement" varchar(500) NOT NULL,
	"text_evenement" text NOT NULL,
	"date_debut" timestamp,
	"heure_debut" varchar(10),
	"heure_fin" varchar(10),
	"all_day" boolean DEFAULT false,
	"is_recurrent" boolean DEFAULT false,
	"rrule" text,
	"duration" varchar(10),
	"exdate" text,
	"author_evenement" varchar(255),
	"category_evenement" varchar(255),
	"color" varchar(50),
	"location" varchar(500),
	"status" varchar(50) DEFAULT 'confirmed',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp
);
